// Generated by `pnpm gen:sample`. Do not edit.
import type * as Twoslash from 'monoshot/twoslash'

import type { Lang } from './protocol.js'

/** The default snippet's language, read from the snippet itself. */
export const language = 'javascript' as const

/** The types the language service finds in the default snippet. */
export const types: { lang: Lang; result: Twoslash.Result } = {
  lang: 'js',
  result: {
    diagnostics: [],
    hovers: [
      {
        from: 9,
        name: 'createHighlighter',
        text: '(alias) const createHighlighter: CreateHighlighterFactory<BundledLanguage, BundledTheme>\nimport createHighlighter',
        to: 26,
      },
      {
        from: 49,
        name: 'highlighter',
        text: 'const highlighter: HighlighterGeneric<BundledLanguage, BundledTheme>',
        to: 60,
      },
      {
        from: 69,
        name: 'createHighlighter',
        text: '(alias) createHighlighter(options: BundledHighlighterOptions<BundledLanguage, BundledTheme>): Promise<HighlighterGeneric<BundledLanguage, BundledTheme>>\nimport createHighlighter',
        to: 86,
      },
      {
        from: 91,
        name: 'langs',
        text: '(property) BundledHighlighterOptions<BundledLanguage, BundledTheme>.langs: (LanguageInput | SpecialLanguage | StringLiteralUnion<BundledLanguage, string>)[]',
        to: 96,
      },
      {
        from: 109,
        name: 'themes',
        text: '(property) BundledHighlighterOptions<BundledLanguage, BundledTheme>.themes: (ThemeInput | "none" | StringLiteralUnion<BundledTheme, string>)[]',
        to: 115,
      },
      {
        from: 145,
        name: 'html',
        text: 'const html: string',
        to: 149,
      },
      {
        from: 152,
        name: 'highlighter',
        text: 'const highlighter: HighlighterGeneric<BundledLanguage, BundledTheme>',
        to: 163,
      },
      {
        from: 164,
        name: 'codeToHtml',
        text: '(property) HighlighterGeneric<BundledLanguage, BundledTheme>.codeToHtml: (code: string, options: CodeToHastOptions<BundledLanguage, BundledTheme>) => string',
        to: 174,
      },
      {
        from: 194,
        name: 'lang',
        text: '(property) lang: "tsx"',
        to: 198,
      },
      {
        from: 209,
        name: 'theme',
        text: '(property) CodeOptionsSingleTheme<BundledTheme>.theme: ThemeRegistrationAny | StringLiteralUnion<BundledTheme, string>',
        to: 214,
      },
      {
        from: 236,
        name: 'html',
        text: 'const html: string',
        to: 240,
      },
    ],
    queries: [
      {
        from: 236,
        name: 'html',
        text: 'const html: string',
        to: 240,
      },
    ],
  },
}
