// Generated by `pnpm gen:sample`. Do not edit.
import type { Lang, Run } from './protocol.js'

/** The default snippet's language, read from the snippet itself. */
export const language = 'javascript' as const

/** The dialect the language service read it as. */
export const lang: Lang = 'js'

/** Ranges twoslash cut from the snippet, as pairs rather than as lists. */
const removals: [number, number][] = [[241, 247]]

/** The run the language service produced for the default snippet. */
export const types: Run = {
  code: "import { createHighlighter } from 'shiki'\n\nconst highlighter = await createHighlighter({\n  langs: ['tsx'],\n  themes: ['vitesse-dark'],\n})\n\nconst html = highlighter.codeToHtml('const a = 1', {\n  lang: 'tsx',\n  theme: 'vitesse-dark',\n})\n\nhtml\n",
  meta: { removals },
  nodes: [
    {
      type: 'hover',
      text: '(alias) const createHighlighter: CreateHighlighterFactory<BundledLanguage, BundledTheme>\nimport createHighlighter',
      docs: 'Initiate a highlighter instance and load the specified languages and themes.\nLater it can be used synchronously to highlight code.\n\nImporting this function will bundle all languages and themes.',
      tags: [
        [
          'see',
          'https://shiki.style/guide/bundles#shiki-bundle-full\n\nFor granular control over the bundle, check:',
        ],
        ['see', 'https://shiki.style/guide/bundles#fine-grained-bundle'],
      ],
      start: 9,
      length: 17,
      target: 'createHighlighter',
      line: 0,
      character: 9,
    },
    {
      type: 'hover',
      text: 'const highlighter: HighlighterGeneric<BundledLanguage, BundledTheme>',
      start: 49,
      length: 11,
      target: 'highlighter',
      line: 2,
      character: 6,
    },
    {
      type: 'hover',
      text: '(alias) createHighlighter(options: BundledHighlighterOptions<BundledLanguage, BundledTheme>): Promise<HighlighterGeneric<BundledLanguage, BundledTheme>>\nimport createHighlighter',
      docs: 'Initiate a highlighter instance and load the specified languages and themes.\nLater it can be used synchronously to highlight code.\n\nImporting this function will bundle all languages and themes.',
      tags: [
        [
          'see',
          'https://shiki.style/guide/bundles#shiki-bundle-full\n\nFor granular control over the bundle, check:',
        ],
        ['see', 'https://shiki.style/guide/bundles#fine-grained-bundle'],
      ],
      start: 69,
      length: 17,
      target: 'createHighlighter',
      line: 2,
      character: 26,
    },
    {
      type: 'hover',
      text: '(property) BundledHighlighterOptions<BundledLanguage, BundledTheme>.langs: (LanguageInput | SpecialLanguage | StringLiteralUnion<BundledLanguage, string>)[]',
      docs: 'Language registation',
      tags: [['default', '[]']],
      start: 91,
      length: 5,
      target: 'langs',
      line: 3,
      character: 2,
    },
    {
      type: 'hover',
      text: '(property) BundledHighlighterOptions<BundledLanguage, BundledTheme>.themes: (ThemeInput | "none" | StringLiteralUnion<BundledTheme, string>)[]',
      docs: 'Theme registation',
      tags: [['default', '[]']],
      start: 109,
      length: 6,
      target: 'themes',
      line: 4,
      character: 2,
    },
    {
      type: 'hover',
      text: 'const html: string',
      start: 145,
      length: 4,
      target: 'html',
      line: 7,
      character: 6,
    },
    {
      type: 'hover',
      text: 'const highlighter: HighlighterGeneric<BundledLanguage, BundledTheme>',
      start: 152,
      length: 11,
      target: 'highlighter',
      line: 7,
      character: 13,
    },
    {
      type: 'hover',
      text: '(property) HighlighterGeneric<BundledLanguage, BundledTheme>.codeToHtml: (code: string, options: CodeToHastOptions<BundledLanguage, BundledTheme>) => string',
      docs: 'Get highlighted code in HTML string',
      start: 164,
      length: 10,
      target: 'codeToHtml',
      line: 7,
      character: 25,
    },
    {
      type: 'hover',
      text: '(property) lang: "tsx"',
      start: 194,
      length: 4,
      target: 'lang',
      line: 8,
      character: 2,
    },
    {
      type: 'hover',
      text: '(property) CodeOptionsSingleTheme<BundledTheme>.theme: ThemeRegistrationAny | StringLiteralUnion<BundledTheme, string>',
      start: 209,
      length: 5,
      target: 'theme',
      line: 9,
      character: 2,
    },
    {
      type: 'hover',
      text: 'const html: string',
      start: 236,
      length: 4,
      target: 'html',
      line: 12,
      character: 0,
    },
    {
      type: 'query',
      text: 'const html: string',
      start: 236,
      length: 4,
      target: 'html',
      line: 12,
      character: 0,
    },
  ],
}
