import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as Twoslash from 'monoshot/twoslash'
import { createTwoslasher } from 'twoslash'

import { detect } from '../src/lib/detect.js'
import { sample } from '../src/lib/sample.js'
import { compilerOptions, dialects } from '../src/lib/twoslash/options.js'

/**
 * Resolves the default snippet's types once, at build time.
 *
 * The worker that resolves them at runtime carries a TypeScript compiler, and
 * a first visit would download it before the reader has typed anything. Regenerate with
 * `pnpm -C app gen:sample` after changing the snippet or the compiler options.
 */
const language = detect(sample) ?? 'tsx'
const lang = dialects[language as keyof typeof dialects] ?? 'ts'
const result = Twoslash.annotate(
  createTwoslasher({
    compilerOptions,
    // Matches the worker: half-typed code is the normal case in an editor, and
    // twoslash otherwise insists every compiler error be declared in the source.
    handbookOptions: { noErrorValidation: true },
  })(sample, lang),
)

const target = path.join(import.meta.dirname, '../src/lib/twoslash/sample.gen.ts')
await fs.writeFile(
  target,
  `// Generated by \`pnpm gen:sample\`. Do not edit.
import type * as Twoslash from 'monoshot/twoslash'

import type { Lang } from './protocol.js'

/** The default snippet's language, read from the snippet itself. */
export const language = ${JSON.stringify(language)} as const

/** The types the language service finds in the default snippet. */
export const types: { lang: Lang; result: Twoslash.Result } = ${JSON.stringify({ lang, result }, null, 2)}
`,
)
console.log(`wrote ${path.relative(process.cwd(), target)}`)
