import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { Twoslash } from 'monoshot'
import { createTwoslasher } from 'twoslash'

import { detect } from '../src/lib/detect.js'
import { sample } from '../src/lib/sample.js'
import { compilerOptions, dialects } from '../src/lib/twoslash/options.js'

/**
 * Resolves the default snippet's types once, at build time.
 *
 * The worker that resolves them at runtime carries a TypeScript compiler, and
 * a first visit would download it before the reader has typed anything. Regenerate with
 * `pnpm -C app gen:sample` after changing the snippet or the compiler options.
 */
const language = detect(sample) ?? 'tsx'
const lang = dialects[language as keyof typeof dialects] ?? 'ts'
const run = createTwoslasher({
  compilerOptions,
  // Matches the worker, so a precomputed snippet reads its tags too.
  customTags: [...Twoslash.tags],
  // Matches the worker: half-typed code is the normal case in an editor, and
  // twoslash otherwise insists every compiler error be declared in the source.
  handbookOptions: { noErrorValidation: true },
})(Twoslash.unchecked(sample), lang)
// The same three fields the worker sends, so a precomputed document and a
// resolved one arrive in one shape.
const types = {
  code: Twoslash.cut(sample, run.meta.removals),
  meta: { removals: run.meta.removals },
  nodes: run.nodes,
}

const target = path.join(import.meta.dirname, '../src/lib/twoslash/sample.gen.ts')
await fs.writeFile(
  target,
  `// Generated by \`pnpm gen:sample\`. Do not edit.
import type { Twoslash } from 'monoshot'

import type { Lang, Run } from './protocol.js'

/** The default snippet's language, read from the snippet itself. */
export const language = ${JSON.stringify(language)} as const

/** The dialect the language service read it as. */
export const lang: Lang = ${JSON.stringify(lang)}

/** Ranges twoslash cut from the snippet, as pairs rather than as lists. */
const removals: [number, number][] = ${JSON.stringify(types.meta.removals)}

/** The types the language service found, as the editor reads them. */
export const result: Twoslash.Result = ${JSON.stringify(Twoslash.annotate(types), null, 2)}

/** The run they were read from, which the frame draws directly. */
export const types: Run = {
  code: ${JSON.stringify(types.code)},
  meta: { removals },
  nodes: ${JSON.stringify(types.nodes, null, 2)},
}
`,
)
console.log(`wrote ${path.relative(process.cwd(), target)}`)
